# .goreleaser.yaml
version: 2
project_name: cntrl

before:
  hooks:
    - go mod tidy
    # Generate Windows resources (icons) before building
    - go-winres make --in winres/winres.json --out cmd/cntrl/

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    main: ./cmd/cntrl
    binary: Cntrl
    ldflags:
      - -s -w -H windowsgui
      - -X main.Version={{.Version}}

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
