//! TypeScript emitter for the JSON Schema subset `cntrl-protocol` produces:
//! objects, string enums, tagged unions, arrays, maps, nullable values and
//! references. Anything else fails code generation, so a new Rust construct
//! can't slip through as a wrong type.

use std::collections::BTreeSet;

use cntrl_protocol::{OpInfo, OpSchema, TopicSchema, close};
use serde_json::{Map, Value};

const HEADER: &str =
    "// Generated by `cargo xtask codegen` from crates/cntrl-protocol. Don't edit.\n";
const INDENT: &str = "    ";

/// `types.ts`: one declaration per schema definition, sorted by name.
pub fn types(defs: &Map<String, Value>) -> Result<String, String> {
    let mut entries: Vec<(&String, &Value)> = defs.iter().collect();
    entries.sort_by(|a, b| a.0.cmp(b.0));
    let mut out = String::from(HEADER);
    for (name, schema) in entries {
        out.push('\n');
        if let Some(text) = description(schema) {
            out.push_str(&doc(text, ""));
        }
        match interface_body(schema)? {
            Some(body) => out.push_str(&format!("export interface {name} {body}\n")),
            None => out.push_str(&format!("export type {name} ={};\n", alias_body(schema)?)),
        }
    }
    Ok(out)
}

/// The right-hand side of a `type` alias. A long union of variants gets one
/// variant per line.
fn alias_body(schema: &Value) -> Result<String, String> {
    let single = ty(schema)?;
    let only_union = schema.as_object().is_some_and(|obj| {
        TYPE_KEYWORDS
            .iter()
            .filter(|key| obj.contains_key(**key))
            .all(|key| *key == "oneOf" || *key == "anyOf")
    });
    let variants = schema
        .get("oneOf")
        .or_else(|| schema.get("anyOf"))
        .and_then(Value::as_array);
    match variants {
        Some(variants) if only_union && single.len() > 80 => {
            let mut body = String::new();
            for variant in variants {
                body.push_str(&format!("\n{INDENT}| {}", paren(&ty(variant)?)));
            }
            Ok(body)
        }
        _ => Ok(format!(" {single}")),
    }
}

/// `ops.ts`: the `Ops` and `Topics` maps and the registry tables.
pub fn ops(ops: &[OpSchema], topics: &[TopicSchema]) -> Result<String, String> {
    let mut imports = BTreeSet::new();
    let mut op_entries = String::new();
    for op in ops {
        let params = ref_name(op.params.as_value())?;
        let result = ref_name(op.result.as_value())?;
        op_entries.push_str(&format!(
            "{INDENT}{}: {{ params: {params}; result: {result}; capability: {}; since: {} }};\n",
            quote(op.info.name)?,
            quote(op.info.capability)?,
            op.info.since
        ));
        imports.extend([params, result]);
    }
    let mut topic_entries = String::new();
    for topic in topics {
        let params = ref_name(topic.params.as_value())?;
        let event = ref_name(topic.event.as_value())?;
        topic_entries.push_str(&format!(
            "{INDENT}{}: {{ params: {params}; event: {event}; capability: {}; since: {} }};\n",
            quote(topic.info.name)?,
            quote(topic.info.capability)?,
            topic.info.since
        ));
        imports.extend([params, event]);
    }
    let imports: Vec<String> = imports.into_iter().collect();

    let mut out = String::from(HEADER);
    out.push_str(&format!(
        "\nimport type {{ {} }} from \"./types\";\n",
        imports.join(", ")
    ));
    out.push_str(
        "\n/** Every operation: its parameters, its result and the policy capability that gates it. */\n",
    );
    out.push_str(&format!(
        "export interface Ops {{\n{op_entries}}}\n\nexport type OpName = keyof Ops;\n"
    ));
    out.push_str(
        "\n/** Every live topic: its parameters, its events and the policy capability that gates it. */\n",
    );
    out.push_str(&format!(
        "export interface Topics {{\n{topic_entries}}}\n\nexport type TopicName = keyof Topics;\n"
    ));
    out.push_str(&registry_table(
        "OPS",
        "The operations registry, in declaration order.",
        ops.iter().map(|op| op.info),
    )?);
    out.push_str(&registry_table(
        "TOPICS",
        "The topics registry, in declaration order.",
        topics.iter().map(|topic| topic.info),
    )?);
    Ok(out)
}

/// `constants.ts`: protocol constants and close codes.
pub fn constants() -> String {
    let mut out = String::from(HEADER);
    out.push('\n');
    out.push_str(&format!(
        "export const PROTOCOL_VERSION = {};\n",
        cntrl_protocol::PROTOCOL_VERSION
    ));
    out.push_str(&format!(
        "export const SUBPROTOCOL = \"{}\";\n",
        cntrl_protocol::SUBPROTOCOL
    ));
    out.push_str(&format!(
        "export const MAX_FRAME_BYTES = {};\n",
        cntrl_protocol::MAX_FRAME_BYTES
    ));
    out.push_str(&format!(
        "export const PING = \"{}\";\n",
        cntrl_protocol::PING
    ));
    out.push_str(&format!(
        "export const PONG = \"{}\";\n",
        cntrl_protocol::PONG
    ));
    out.push_str(
        "\n/** WebSocket close codes. 1000 to 1013 are from the IANA registry; 4000 to 4999 are private use. */\n",
    );
    out.push_str("export const CloseCode = {\n");
    for (name, code) in close::ALL {
        out.push_str(&format!("{INDENT}{name}: {code},\n"));
    }
    out.push_str(
        "} as const;\n\nexport type CloseCode = (typeof CloseCode)[keyof typeof CloseCode];\n",
    );
    out
}

fn registry_table(
    name: &str,
    doc_text: &str,
    entries: impl Iterator<Item = OpInfo>,
) -> Result<String, String> {
    let mut out = format!("\n/** {doc_text} */\nexport const {name} = [\n");
    for info in entries {
        out.push_str(&format!(
            "{INDENT}{{ name: {}, capability: {}, since: {} }},\n",
            quote(info.name)?,
            quote(info.capability)?,
            info.since
        ));
    }
    out.push_str("] as const;\n");
    Ok(out)
}

/// The body of an `interface`, when the schema is a plain object with named
/// properties and nothing to combine.
fn interface_body(schema: &Value) -> Result<Option<String>, String> {
    let Some(obj) = schema.as_object() else {
        return Ok(None);
    };
    let combines = [
        "$ref",
        "allOf",
        "anyOf",
        "oneOf",
        "enum",
        "const",
        "additionalProperties",
    ]
    .iter()
    .any(|key| obj.contains_key(*key));
    if combines || !has_properties(obj) {
        return Ok(None);
    }
    let mut body = String::from("{\n");
    for field in fields(obj)? {
        if let Some(text) = &field.doc {
            body.push_str(&doc(text, INDENT));
        }
        let optional = if field.optional { "?" } else { "" };
        body.push_str(&format!(
            "{INDENT}{}{optional}: {};\n",
            field.name, field.ty
        ));
    }
    body.push('}');
    Ok(Some(body))
}

/// Keywords that give a schema a type; a schema with none of them accepts
/// anything.
const TYPE_KEYWORDS: [&str; 11] = [
    "$ref",
    "const",
    "enum",
    "oneOf",
    "anyOf",
    "allOf",
    "properties",
    "type",
    "items",
    "prefixItems",
    "additionalProperties",
];

/// The TypeScript type of one schema.
fn ty(schema: &Value) -> Result<String, String> {
    let obj = match schema {
        Value::Bool(true) => return Ok("unknown".to_owned()),
        Value::Object(obj) => obj,
        other => return Err(format!("unsupported schema: {other}")),
    };
    // Annotations alone, such as `{"default": null}` on a raw JSON field,
    // constrain nothing.
    if !TYPE_KEYWORDS.iter().any(|key| obj.contains_key(*key)) {
        return Ok("unknown".to_owned());
    }
    let mut parts = Vec::new();
    if obj.contains_key("$ref") {
        parts.push(ref_name(schema)?);
    }
    if let Some(value) = obj.get("const") {
        parts.push(literal(value)?);
    }
    if let Some(values) = obj.get("enum") {
        let values = values.as_array().ok_or("`enum` isn't an array")?;
        let literals = values.iter().map(literal).collect::<Result<Vec<_>, _>>()?;
        parts.push(literals.join(" | "));
    }
    for key in ["oneOf", "anyOf"] {
        if let Some(variants) = obj.get(key) {
            let variants = variants
                .as_array()
                .ok_or_else(|| format!("`{key}` isn't an array"))?;
            let types = variants
                .iter()
                .map(|variant| ty(variant).map(|t| paren(&t)))
                .collect::<Result<Vec<_>, _>>()?;
            parts.push(types.join(" | "));
        }
    }
    if let Some(all) = obj.get("allOf") {
        for part in all.as_array().ok_or("`allOf` isn't an array")? {
            parts.push(ty(part)?);
        }
    }
    if has_properties(obj) {
        parts.push(inline_object(obj)?);
    } else if parts.is_empty()
        && let Some(kind) = obj.get("type")
    {
        parts.push(type_keyword(obj, kind)?);
    }
    match parts.len() {
        0 => Err(format!("unsupported schema: {schema}")),
        1 => Ok(parts.swap_remove(0)),
        _ => Ok(parts
            .iter()
            .map(|part| paren(part))
            .collect::<Vec<_>>()
            .join(" & ")),
    }
}

fn has_properties(obj: &Map<String, Value>) -> bool {
    obj.get("properties")
        .and_then(Value::as_object)
        .is_some_and(|properties| !properties.is_empty())
}

fn type_keyword(obj: &Map<String, Value>, kind: &Value) -> Result<String, String> {
    match kind {
        Value::String(kind) => keyword(obj, kind),
        Value::Array(kinds) => {
            let types = kinds
                .iter()
                .map(|kind| {
                    kind.as_str()
                        .ok_or_else(|| format!("unsupported `type`: {kind}"))
                        .and_then(|kind| keyword(obj, kind))
                })
                .collect::<Result<Vec<_>, _>>()?;
            Ok(types.join(" | "))
        }
        other => Err(format!("unsupported `type`: {other}")),
    }
}

fn keyword(obj: &Map<String, Value>, kind: &str) -> Result<String, String> {
    match kind {
        "string" => Ok("string".to_owned()),
        "integer" | "number" => Ok("number".to_owned()),
        "boolean" => Ok("boolean".to_owned()),
        "null" => Ok("null".to_owned()),
        "array" => array(obj),
        "object" => match obj.get("additionalProperties") {
            None | Some(Value::Bool(false)) => Ok("{ [key: string]: never }".to_owned()),
            Some(value) => Ok(format!("{{ [key: string]: {} }}", ty(value)?)),
        },
        other => Err(format!("unsupported type `{other}`")),
    }
}

fn array(obj: &Map<String, Value>) -> Result<String, String> {
    if let Some(items) = obj.get("prefixItems").and_then(Value::as_array) {
        let types = items.iter().map(ty).collect::<Result<Vec<_>, _>>()?;
        return Ok(format!("[{}]", types.join(", ")));
    }
    let item = obj.get("items").ok_or("array without `items`")?;
    Ok(format!("{}[]", paren(&ty(item)?)))
}

struct Field {
    name: String,
    optional: bool,
    ty: String,
    doc: Option<String>,
}

fn fields(obj: &Map<String, Value>) -> Result<Vec<Field>, String> {
    let properties = obj
        .get("properties")
        .and_then(Value::as_object)
        .ok_or("object without `properties`")?;
    let required: Vec<&str> = obj
        .get("required")
        .and_then(Value::as_array)
        .map(|names| names.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    properties
        .iter()
        .map(|(name, schema)| {
            Ok(Field {
                name: property_name(name),
                optional: !required.contains(&name.as_str()),
                ty: ty(schema)?,
                doc: description(schema).map(str::to_owned),
            })
        })
        .collect()
}

fn inline_object(obj: &Map<String, Value>) -> Result<String, String> {
    let members: Vec<String> = fields(obj)?
        .iter()
        .map(|field| {
            let optional = if field.optional { "?" } else { "" };
            format!("{}{optional}: {}", field.name, field.ty)
        })
        .collect();
    Ok(format!("{{ {} }}", members.join("; ")))
}

fn description(schema: &Value) -> Option<&str> {
    schema.get("description").and_then(Value::as_str)
}

fn doc(text: &str, indent: &str) -> String {
    // Rustdoc links (``[`Name`]``) become JSDoc links.
    let text = &text.replace("[`", "{@link ").replace("`]", "}");
    if !text.contains('\n') {
        return format!("{indent}/** {text} */\n");
    }
    let mut out = format!("{indent}/**\n");
    for line in text.lines() {
        if line.is_empty() {
            out.push_str(&format!("{indent} *\n"));
        } else {
            out.push_str(&format!("{indent} * {line}\n"));
        }
    }
    out.push_str(&format!("{indent} */\n"));
    out
}

fn ref_name(schema: &Value) -> Result<String, String> {
    schema
        .get("$ref")
        .and_then(Value::as_str)
        .and_then(|reference| reference.strip_prefix("#/$defs/"))
        .map(str::to_owned)
        .ok_or_else(|| format!("expected a reference to a named type, found {schema}"))
}

fn literal(value: &Value) -> Result<String, String> {
    match value {
        Value::String(_) | Value::Number(_) | Value::Bool(_) | Value::Null => Ok(value.to_string()),
        other => Err(format!("unsupported literal: {other}")),
    }
}

fn property_name(name: &str) -> String {
    let mut chars = name.chars();
    let valid = chars
        .next()
        .is_some_and(|c| c == '_' || c == '$' || c.is_ascii_alphabetic())
        && chars.all(|c| c == '_' || c == '$' || c.is_ascii_alphanumeric());
    if valid {
        name.to_owned()
    } else {
        Value::String(name.to_owned()).to_string()
    }
}

fn quote(text: &str) -> Result<String, String> {
    if text
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '.' || c == '_')
    {
        Ok(format!("\"{text}\""))
    } else {
        Err(format!("unexpected character in registry name `{text}`"))
    }
}

fn paren(ty: &str) -> String {
    if ty.contains(" | ") || ty.contains(" & ") {
        format!("({ty})")
    } else {
        ty.to_owned()
    }
}
